### ISSUE TITLE
Missing options c1 and c2 with kallistobustools count

### ISSUE THREAD

**Issue by Khajidu** [nf-core/scrnaseq#123]
### Description of the bug

Whenever I launch scrnaseq with `--aligner kallisto`, it crashes at the counting step with the following error message: `kb count: error: the following arguments are required: -c1, -c2`. Is something missing from the previous steps?

### Command used and terminal output

```console
nextflow run nf-core/scrnaseq -resume --max_memory '500.GB' -r dev -c /shared/home/hmayeur/.nextflow/config --outdir /shared/ifbstor1/projects/bsbii/sc_single_cell_brain/fulltest/ --protocol '10XV3' --aligner kallisto --transcript_fasta /shared/projects/bsbii/sc_single_cell_brain/sc_gene_models_ncbi_utrs.fasta --input 'test_samples_v2.csv' --genome_fasta /shared/projects/bsbii/sc_single_cell_brain/sc_ncbi_genome.fasta --gtf /shared/projects/bsbii/sc_single_cell_brain/sc_gene_models_ncbi_no_genes_no_contigs_notrnas.gtf --kb_workflow 'nucleus' -profile ifb_core
```

### System information

Nextflow version : 22.04.0
Hardware : HPC
Executor : Slurm
Container : Singularity
OS : CentOS
Version of nf-core/scrnaseq : 2.0.0 or dev

**Comment by apeltzer** [comment]
PR is open for a fix for this, not long and it should work perfectly fine then.

**Comment by apeltzer** [comment]
Should be fine with `dev` now - please give this a spin and reopen if the problem persists 👍🏻 @Khajidu
