### ISSUE TITLE
Add option to run CellRanger in nuclei mode

### ISSUE THREAD

**Issue by esrice** [nf-core/scrnaseq#130]
### Description of feature

I frequently use CellRanger for nuclei data. It now supports nuclei data through the `--include-introns` flag without needing a specially built index containing introns as it did before. There is an option in this pipeline to run kallisto in 'nucleus' mode but none for CellRanger.

I am about to start working on this myself, and so I am adding this feature request as advised in the contribution guidelines :)

**Comment by apeltzer** [comment]
Go for it ;-)

**Comment by esrice** [comment]
Just realized v7 of CellRanger decided that including introns was the right way to go for both single cell and single nucleus libraries, so it does this behavior by default. So never mind this, sorry 🤦

**Comment by apeltzer** [comment]
Ok, good that its already there then :-)
