### ISSUE TITLE
No matrix file in STAR outputs

### ISSUE THREAD

**Issue by Vivian-chen16** [nf-core/scrnaseq#134]
### Description of the bug

Hello,

I've successfully finished running scrnaeq with `--aligner star` on single AWS instance but couldn't find the count results (i.e. barcode.tsv, features.tsv and matrix.mtx) in the out directory.  The output structure I had is identical as this: https://nf-co.re/scrnaseq/results#scrnaseq/results-27f37ab827b3f72e8e305256a9c59a37bb85ef83/aligner_star/star/
Is there any other options I should include to generate them? 

Any suggestions are appreciated!

### Command used and terminal output

```console
$ nextflow run nf-core/scrnaseq --input sample21476_CTX-sheet.csv --outdir sample21476_CTX --genome_fasta ./refdata-gex-GRCh38-2020-A/fasta/genome.fa --gtf ./refdata-gex-GRCh38-2020-A/genes/genes.gtf --protocol 10XV2 --aligner star -profile docker -bg
```

### Relevant files

![Screen Shot ](https://user-images.githubusercontent.com/53973160/181066636-c8598166-2035-4d30-ac08-d61a3b48b68e.png)

**Comment by Vivian-chen16** [comment]
For those who also wonder about this - the rest of STAR outputs are actually under `work` directory rather than `outdir`.

**Comment by grst** [comment]
If they are not getting published to the results directory, that's a bug (which should be easy to fix)!

One should never have to look into the work dir to obtain results.

**Comment by Vivian-chen16** [comment]
fixed in [added an option to convert star count matrix](https://github.com/nf-core/scrnaseq/commit/88289cca2fea04aed10fe00786ade69c83202613) !
