### ISSUE TITLE
Support for single nucleus RNA-seq data

### ISSUE THREAD

**Issue by galanisl** [nf-core/scrnaseq#137]
### Description of feature

It would be great if the `kallisto` options to build an appropriate index for snRNA-seq (i.e., a custom built DNA and intron index) and to properly generate count matrices for this type of dataset are made available. See here: https://www.kallistobus.tools/tutorials/kb_nucleus/python/kb_single_nucleus/

**Comment by ogibson** [comment]
Looking at this issue it's not clear to me why Kallisto count doesn't use --workflow as a parameter. Was this a conscious decision? 

The straightforward way to address the issue would be to add the parameter in count, as the rest of the code is already in place to support intron output in the ref function.

**Comment by apeltzer** [comment]
We're relying on kbpython to do this - have a look: https://github.com/nf-core/scrnaseq/blob/c86646e4a818397f4bddfffd641b34240423f3ea/conf/modules.config#L131

**Comment by apeltzer** [comment]
So it should already be possible to set this, just by using the correct `kb_workflow` - mind creating a test case for it so we can also ensure this is being tested for downstream compatibility with other tools in the pipeline?

**Comment by ogibson** [comment]
My bad -- missed that.

It looks like the issue should be closed. I'll look into adding a test case!
