### ISSUE TITLE
kallisto output in h5ad and/or loom format

### ISSUE THREAD

**Issue by galanisl** [nf-core/scrnaseq#138]
### Description of feature

It would be great to include an option to select the desired `kallisto` output format. Depending on the tool chosen for downstream analysis, the `h5ad` or `loom` formats would be more convenient than the raw `mtx`, `barcode` and `cell` files.

This can be achieved by passing `--h5ad` or `--loom` to `kb count` .

**Comment by grst** [comment]
The `dev` version of the pipeline already generates a `h5ad` file independent of the chosen aligner. 
Do the `h5ad` files generated by kallisto have any advantages over that?

**Comment by galanisl** [comment]
Not at all. I will test the `dev` version of the pipeline then. Thanks a lot.
