### ISSUE TITLE
More columns in samplesheet

### ISSUE THREAD

**Issue by grst** [nf-core/scrnaseq#150]
### Description of feature

It should be possible to set the following information in the samplesheet on a per-sample basis: 

 * expected_cells (Used at least by cellranger and starsolo, don't know if kallisto/salmon can also use this parameter)
 * `seq_center` (Stored as metadata in BAM files, currently this can only bet set globally for the entire pipeline)

**Comment by apeltzer** [comment]
At least CellRanger 7.0.0 doesn't need it anymore to be set -- https://software.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/release-notes

**Comment by grst** [comment]
> How common a use case is it to process data from multiple sequencing centres in a single pipeline run

I would have liked to do this when reprocessing publicly available single-cell data, e.g. to build an atlas consisting of multiple datasets. 

> hould this be removed from the example until the above is implemented?

Additional columns don't harm, it's safe to keep it there. 

> At least CellRanger 7.0.0 doesn't need it anymore to be set 

Ok, that reduces the priority - but it is still a valid parameter supported by multiple aligners.

**Comment by grst** [comment]
Actually, would something like this work to make use of arbitrary columns in the samplesheet? 

```nextflow
process {
    withName: CELLRANGER {
        ext.args = { "--expect-cells ${meta['expected_cells']}" }
    }
}
```

But anyway, common options (that would usually get a `--param`) that are sample-specific should go into the samplesheet and we should have a mechanism for that.

**Comment by ameynert** [comment]
> Additional columns don't harm, it's safe to keep it there.

Agree it doesn't affect the pipeline, but new users may expect a parameter to do something if it's present in an example. With 3 of the 4 workflows supporting expected cell count, agree it should stay as a feature request.

- Alevin - yes - [https://salmon.readthedocs.io/en/latest/alevin.html#expectcells]
- CellRanger - yes, though auto estimation recommended [https://software.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/release-notes]
- Kallisto - no - only reference I can find is for generating a downstream plot [https://www.kallistobus.tools/tutorials/kb_building_atlas/python/kb_analysis_0_python/?h=expect#examine-the-knee-plot]
- STARsolo - yes - [https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md]

**Comment by ameynert** [comment]
- [x] Parsing expected_cells and seq_center from samplesheet into meta
- [x] STARsolo
- [ ] Alevin
  - waiting on new Conda package & bioconda update; fix was required in https://github.com/COMBINE-lab/simpleaf/tree/main
- [ ] Cellranger
  - PR https://github.com/nf-core/modules/pull/2251 for modules/cellranger/count
  - Will update modules.json with new git_sha when above approved
