### ISSUE TITLE
Matrix conversions should provide gene annotations

### ISSUE THREAD

**Issue by ogibson** [nf-core/scrnaseq#159]
### Description of feature

All the mtx_conversions that are being generated by the pipeline are output without the annotations for the features, providing only the Ensembl ids and not the symbols. Except in the case of Alevin it should be pretty straightforward to export the annotations (if available) in the mtx conversions.

Any thoughts on this?

**Comment by grst** [comment]
at least in the anndata and seurat objects we should definitely have them. Shouldn't be to complicated to get them from the GTF file?
