### ISSUE TITLE
Add intronic quantification to star for single nuclei

### ISSUE THREAD

**Issue by Vivian-chen16** [nf-core/scrnaseq#161]
### Description of feature

It'd be useful that all aligners can deal with introns in single nuclei dataset. Now seems only star hasn't covered. 

CellRanger -[ include introns](https://support.10xgenomics.com/docs/intron-mode-rec?src=social&lss=facebook&cnm=soc-fb-ra_g-program&cid=7011P000000y072) is set as default in latest version and recommended to turn on for both single cell and single nuclei while it's still nice to have the option for user to choose.
Kallisto - #137 has covered

Also, I wonder if it's better to implement this feature as global parameter, like [RNA velocity](https://github.com/nf-core/scrnaseq/issues/14), or it's good enough to have it as another option under each aligner?

**Comment by grst** [comment]
> Also, I wonder if it's better to implement this feature as global parameter, like https://github.com/nf-core/scrnaseq/issues/14, or it's good enough to have it as another option under each aligner?

It would be good enough, I'd say, but a global option would be somewhat cooler. 

You split the issues for presets and this (which I think is good to move this forward), but I actually started wondering if global settings like RNA velocity or single nuclei could be solved via presets, e.g. 

```
> nextflow run nf-core/scrnaseq --preset velocity
```

or maybe even

```
> nextflow run nf-core/scrnaseq --preset velocity,single_nucleus
```

A preset can be defined for one or multiple aligners, choosing the proper settings. If a preset is chosen that is not implemented for a certain aligner, it fails

```
> nextflow run nf-core/scrnaseq --preset starsolo_10x_like --aligner kallisto

Error: The preset starsolo_10x_like is not implemented for aligner kallisto. 
```


Just and idea for you to discuss at the hackathon ;)

**Comment by Vivian-chen16** [comment]
> but I actually started wondering if global settings like RNA velocity or single nuclei could be solved via presets

Good point, current structure in [kallisto](https://nf-co.re/scrnaseq/2.1.0/parameters#kallistobus-options) also looks straightforward enough for users to adjust based on their need. If we’re using the similar naming convention for star, it won't be too confusing, in my opinion.  How about starting with individual option, one step at a time, but flexible to upgrade at some points?




This looks great!!
```
> nextflow run nf-core/scrnaseq --preset starsolo_10x_like --aligner kallisto

Error: The preset starsolo_10x_like is not implemented for aligner kallisto. 
```


Much appreciate (my brain doesn't cooperate well with the time difference but I'd love to work on this)!!

**Comment by grst** [comment]
> How about starting with individual option, one step at a time, but flexible to upgrade at some points?

Fair enough! Just start a PR adding the minimal necessary functionality, and we can continue the discussion from there :)

**Comment by grst** [comment]
Conceptually, having a list of presets isn't much different of having a `--flag` for each preset, i.e

```
--starsolo_10x_like --velocity
```

vs.

```
--preset starsolo_10x_like,velocity
```

I for the preset option I was inspired by the kallistobustools `--workflow` parameter. Not sure what makes more sense :shrug:

**Comment by Vivian-chen16** [comment]
For `starsolo_10x_like` one, it's more about taking extra arguments in than switching between options for certain argument. I would vote for having different `--flag` in this case but would love to hear what others think as always!
