### ISSUE TITLE
--fasta and --gtf not recognised

### ISSUE THREAD

**Issue by birgitritschka** [nf-core/scrnaseq#172]
### Description of the bug

Trying to run scRNAseq on an HPC with --fasta and --gtf, keep getting error :

`Unknown option: -—fasta -- Check the available commands and options and syntax with 'help'`

I have tried putting the nextflow options at the beginning or end, but always it cannot find --fasta or --gtf.

Am I doing something silly here? Are there any obvious ways to debug what I'm doing wrong

### Command used and terminal output

```console
nextflow run main.nf --outdir 'Test_birgit_out' --input 'Samplesheet.csv' -—fasta '/scratch-cbe/users/birgit.ritschka/Nextflow_scRNA-Seq/XENLA_10.1_genome.fna.gz' -—gtf '/scratch-cbe/users/birgit.ritschka/Nextflow_scRNA-Seq/XENLA_10.1_GCF_XBmodels.gff3.gz' --aligner 'cellranger' --protocol ’10XV2’ -bg -profile cbe

[birgit.ritschka@clip-login-1 Nextflow_scRNA-Seq_Run2]$ Unknown option: -—fasta -- Check the available commands and options and syntax with 'help'
```
```


### Relevant files

_No response_

### System information

Nextflow Version: 22.10.0 build 5826
  Created: 13-10-2022 05:44 UTC (07:44 CEST)
  System: Linux 3.10.0-1160.62.1.el7.x86_64
  Runtime: Groovy 3.0.13 on OpenJDK 64-Bit Server VM 11.0.2+9
  Encoding: UTF-8 (UTF-8)
  
  HPC/Slurm
Singularity
Linux
nfcore scrnaseq 2.1.0

**Comment by fmalmeida** [comment]
Hello @birgitritschka,
From the copy paste and the console messages, it seems that the `--` dashes were not rendering the command line when you copied.

Your `--fasta` looks like `-—`.

Can you try running again but, that time, deleting and manually typing again the dashes?

Just to see whether this is the case. And, if not, we can try to figure it out.
