### ISSUE TITLE
Should save_reference parameter be boolean?

### ISSUE THREAD

**Issue by tomsing1** [nf-core/scrnaseq#173]
https://github.com/nf-core/scrnaseq/blob/c86646e4a818397f4bddfffd641b34240423f3ea/nextflow_schema.json#L118

The schema requires a string (perhaps 'true' or 'false')? The equivalent parameter in the rnaseq pipeline requires a boolean value. Should that be the type for the scrnaseq pipeline, too?

**Comment by apeltzer** [comment]
Yes it should, so this is a bug 👍🏻

**Comment by fmalmeida** [comment]
Looking at the code to fix it ... I saw that actually this `params.save_reference` is not being used anywhere

<img width="357" alt="image" src="https://user-images.githubusercontent.com/7727714/200834350-e4d63ac5-719d-41e2-884a-7122ffc29125.png">

where should it actually go? then I can fix them all at once

**Comment by grst** [comment]
If one of index steps (cellranger mkref, salmon index, ...) runs, the index files should be published to the output directories if this flag is set, but not by default.

**Comment by fmalmeida** [comment]
But, I could not find anywhere in the pipeline where the parameter is being used.

**Comment by grst** [comment]
yes, so it should be used in the `modules.config` to set the publishDir
directives for these processes accordingly

**Comment by fmalmeida** [comment]
Fix for it has been opened on https://github.com/nf-core/scrnaseq/pull/181

**Comment by fmalmeida** [comment]
Closing it since PR #181 has been merged.
