### ISSUE TITLE
Add multiome support (scATAC + scRNA)

### ISSUE THREAD

**Issue by heylf** [nf-core/scrnaseq#174]
### Description of feature

Just wanted to put it down and mention that I am currently working on the implementation of cellranger-arc (modules + subworkflow). Maybe worth to discuss if this is fine to integrate into scranseq or if his should be an own pipeline as it requires a different sample sheet format and different input checks.

**Comment by grst** [comment]
Could you elaborate on how the samplesheet would need to look like? If it's just about having additional columns, I think it would be fine. 

More general, we should think about which modalities (ATAC, CITE, VDJ, spatial, ...) we want to support in the future and which should be processed by the same workflow.

**Comment by heylf** [comment]
I will implement cellranger-arc in scrnaseq and then see how it goes. But yes, it would be nice to discuss the modalities.

**Comment by apeltzer** [comment]
Would still be great to discuss here before merging an entire subworkflow first 😉

**Comment by heylf** [comment]
Technically cellranger-arc needs a samplesheet (lib.cv) as an input which looks likes this:

```
fastqs,sample,library_type
/home/jdoe/runs/HNGEXSQXXX/outs/fastq_path,example,Gene Expression
/home/jdoe/runs/HNATACSQXX/outs/fastq_path,example,Chromatin Accessibility
```

Thus, lib.csv defines the folder locations for the scRNA and scATAC for the sample. 

My thinking was the following:
1. Keep the definitions, subworkflows, and modules for the samplesheet as it is currently defined for scrnaseq
2. Add two new optional columns to the samplesheet: `folder_GEX` and `folder_ATAC`
3. Write a separate input_check_multiome.nf to create an input channel for scranseq.nf that has instead of `[meta, [reads]]` now  `[meta, [folders]]`
4. Write a module and script to generate the lib.csv for cellranger based on the input channel from step 3. 

This approach could be thus easily adapted for future data modalities (e.g., an additional methylation data) if this arrives at some point. 

What are your thoughts about this? @grst and @apeltzer

**Comment by grst** [comment]
Personally I like to have all files explicitly listed in the samplesheet, also for consistency with other aligners. 

Possible alternative:
Add an additional column `sample_type` to the samplesheet. The column is optional and if nothing is specified it assumes "gex":
```csv
sample,fastq_1,fastq_2,expected_cells,sample_type
pbmc8k,s3://nf-core-awsmegatests/scrnaseq/input_data/pbmc8k_S1_L007_R1_001.fastq.gz,s3://nf-core-awsmegatests/scrnaseq/input_data/pbmc8k_S1_L007_R2_001.fastq.gz,"10000",gex
pbmc8k,s3://nf-core-awsmegatests/scrnaseq/input_data/pbmc8k_S1_L008_R1_001.fastq.gz,s3://nf-core-awsmegatests/scrnaseq/input_data/pbmc8k_S1_L008_R2_001.fastq.gz,"10000",gex
pbmc8k,s3://nf-core-awsmegatests/scrnaseq/input_data/pbmc8k_S1_L007_R1_001.fastq.gz,s3://nf-core-awsmegatests/scrnaseq/input_data/pbmc8k_S1_L007_R2_001.fastq.gz,"10000",atac
pbmc8k,s3://nf-core-awsmegatests/scrnaseq/input_data/pbmc8k_S1_L008_R1_001.fastq.gz,s3://nf-core-awsmegatests/scrnaseq/input_data/pbmc8k_S1_L008_R2_001.fastq.gz,"10000",atac
```

**Comment by heylf** [comment]
Works for me.

**Comment by apeltzer** [comment]
Tendency to go for the option proposed by @grst as it will not break existing solutions / setup 👍🏻

**Comment by heylf** [comment]
Perfect. Then I am on it!

**Comment by heylf** [comment]
Thanks @apeltzer. Indeed, also for findability, because users might not immediately realize that you could use scrnaseq for scATAC and multiome.

**Comment by apeltzer** [comment]
Link to discussion on Slack also added here to do proper x-ref: https://nfcore.slack.com/archives/CE4K7FEHE/p1667987775811819

**Comment by apeltzer** [comment]
Please chime in there too - there is some opinions out there.

**Comment by grst** [comment]
both cellranger-arc and cellranger-multi are implemented. 
Although cellranger-arc still needs tests (#290)
