### ISSUE TITLE
Cannot switch to revision: 1.0.0

### ISSUE THREAD

**Issue by mdeloger** [nf-core/scrnaseq#18]
Hi @PeterBailey ,

I have just cloned the git repository of the "scrnaseq" pipeline and when I try to launch it, here the message I obtain : 

nextflow run nf-core/scrnaseq -r 1.0.0 -profile conda,test
N E X T F L O W  ~  version 19.10.0
Project `nf-core/scrnaseq` contains uncommitted changes -- Cannot switch to revision: 1.0.0

May I have some help please ?

Thank you in advance

**Comment by apeltzer** [comment]
Probably you cloned it once already and are stuck in a previous git head. 

`rm -rf ~/.nextflow/assets/nf-core/scrnaseq`

and then repull ?

**Comment by mdeloger** [comment]
It was my first clone of this repository but I tried your solution and here what it comes :
 
-bash-4.2$ rm -rf .nextflow
-bash-4.2$ /bioinfo/local/build/Centos/nextflow/nextflow run nf-core/scrnaseq -r 1.0.0 -profile conda,test
N E X T F L O W  ~  version 19.10.0
Project `nf-core/scrnaseq` contains uncommitted changes -- Cannot switch to revision: 1.0.0

**Comment by mdeloger** [comment]
And : 

-bash-4.2$ git pull
Already up to date.

**Comment by mdeloger** [comment]
oh ok it was the .nextflow in the home and not the local one.
you are right, sorry

thank you :-)
