### ISSUE TITLE
update conversion scripts to auto-detect matrix shape

### ISSUE THREAD

**Issue by fmalmeida** [nf-core/scrnaseq#188]
### Description of feature

Instead of relying on the aligner, since versions of the same aligner ""may"" have different shapes. It would be good to change the conversion scripts to auto-detect the shape of matrix and select when to transposer based on that.

e.g

From.
```python
if (
        aligner == "star"
    ):  # for some reason star matrix comes transposed and doesn't fit when values are appended directly
        adata = adata.transpose()
```

To.
```python
    matrix_1st_col = pd.read_csv( args["mtx"], sep=' ', comment='%', header=None ).head()[0][0]
    feature_lines  = pd.read_csv( args["feature"], sep=' ', comment='%', header=None ).shape[0]
    
    # scanpy expects feature "info" to be on the second column
    if int(matrix_1st_col) == int(feature_lines):
         is_transposed = True
    else:
         is_transposed = False

    if is_transposed:  
        adata = adata.transpose()
```

What do you guys think? @apeltzer ; @grst

**Comment by apeltzer** [comment]
Would be less dependent on the upstream method then yes, which is good. Not sure that we "gain" a lot here though.

**Comment by fmalmeida** [comment]
Don’t know how often this could happen, but it makes sense.

I’ll close the issue :)
