### ISSUE TITLE
Inconsistent default protocol 

### ISSUE THREAD

**Issue by martinkim0** [nf-core/scrnaseq#189]
### Description of the bug

Currently, `nextflow_schema.json` lists 10XV2 as the default protocol, so that is what is displayed in the docs. However, it looks like 10XV3 is actually the default being used as seen in `nextflow.config`. 

### System information

nf-core/scrnaseq dev

**Comment by grst** [comment]
And it should actually be removed from both and be part of the samplesheet, s.t. protocol can bet set on a per-sample basis. 

I thought this was implemented long time ago. @fmalmeida, @apeltzer?

@ameynert removed the protocol from the test samplesheet in https://github.com/nf-core/test-datasets/commit/fdd2d2b51103034e9a11f98c807eec86a0997bc8. Did I miss something (maybe during the hackathon) or was it just not implemented and therefore removed from the samplesheet to not be misleading?

**Comment by apeltzer** [comment]
Guess that was not implemented but would have to dig myself what in the end was (not) done.

**Comment by grst** [comment]
Fixed in dev. The default protocol is now "auto" for 10x.
