### ISSUE TITLE
Increase time limit for alevinQC

### ISSUE THREAD

**Issue by FelixKrueger** [nf-core/scrnaseq#196]
### Description of the bug

The scrna workflow consistently failed to run to completion for some public single-cell data sets (Guan 2022, [GSE178325](http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE178325) [GSE176381](http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE176381)) with the error message:

```nextflow
Error executing process > 'NFCORE_SCRNASEQ:SCRNASEQ:SCRNASEQ_ALEVIN:ALEVINQC (SRR15595209_GSM5534149_StageIII_Day8-0618-2_Homo_sapiens_RNA-Seq)'

Caused by:
  Job attempt duration exceeded timeout

Command executed:

  #!/usr/bin/env Rscript
  require(alevinQC)
  alevinFryQCReport(
      mapDir = "SRR15595209_GSM5534149_StageIII_Day8-0618-2_Homo_sapiens_RNA-Seq_alevin_results/af_map",
      quantDir = "SRR15595209_GSM5534149_StageIII_Day8-0618-2_Homo_sapiens_RNA-Seq_alevin_results/af_quant",
      permitDir= "SRR15595209_GSM5534149_StageIII_Day8-0618-2_Homo_sapiens_RNA-Seq_alevin_results/af_quant",
      sampleId = "SRR15595209_GSM5534149_StageIII_Day8-0618-2_Homo_sapiens_RNA-Seq",
      outputFile = "alevin_report_SRR15595209_GSM5534149_StageIII_Day8-0618-2_Homo_sapiens_RNA-Seq.html",
      outputFormat = "html_document",
      outputDir = "./",
      forceOverwrite = TRUE
  )
 ```

Allowing this step more time with the following addition to the Nextflow config worked like a treat:

```nextflow
process {
    withName: 'NFCORE_SCRNASEQ:SCRNASEQ:SCRNASEQ_ALEVIN:ALEVINQC' {
        time = '20.h'
    }
}
```

According to a communication on Slack the process is normally labelled as `process_low` (time limit = 4.h), but the tasks took between 5 and 6h to complete (thanks to @drpatelh and @fmalmeida for their helpful comments). 

Many thanks for adding this for the next release! Cheers, Felix

**Comment by apeltzer** [comment]
See PR #197

**Comment by grst** [comment]
The QC should definitely not take that long. 
@FelixKrueger, would you mind creating an issue upstream?

**Comment by klkeys** [comment]
looks fixed, move to close
