### ISSUE TITLE
Pipeline does not detect transcriptome_fasta argument

### ISSUE THREAD

**Issue by jma1991** [nf-core/scrnaseq#20]
The pipeline does not detect when I provide a transcriptome fasta file. Instead, it produces the following error:

```
$ /home/jashmore/anaconda3/envs/nextflow/bin/nextflow run nf-core/scrnaseq --reads 'data/reads/*_R{1,2}.fastq.gz' --type 10x --chemistry V2 --aligner alevin --salmon_index data/genomes/index/salmon --txp2gene data/genomes/txp2gene.csv --transcriptome_fasta data/genomes/transcriptome.fa
N E X T F L O W  ~  version 19.10.0
Launching `nf-core/scrnaseq` [marvelous_mcclintock] - revision: 884e541285 [master]
Neither of --fasta or --transcriptome provided! At least one must be provided to quantify genes
```
The error message is also slightly wrong as there is actually no argument called "--transcriptome", instead it is "--transcriptome_fasta" in the documentation. I think the error may be caused by a mistake in the variable naming in the main.nf file (lines 107 - 110). Shouldn't the params variable refer to params.transcriptome_fasta not params.transcript_fasta?

```
if (!params.fasta && !params.transcript_fasta){
  exit 1, "Neither of --fasta or --transcriptome provided! At least one must be provided to quantify genes"
}
```

Thank you,
James

**Comment by apeltzer** [comment]
Pull Request https://github.com/nf-core/scrnaseq/pull/22 should fix this issue - you can for example test using this here and replacing [...] with your parameters of choice:

```
nextflow run apeltzer/scrnaseq -r dev [....]
```
