### ISSUE TITLE
Auto rename fastq files for cellranger input

### ISSUE THREAD

**Issue by vjmarteau** [nf-core/scrnaseq#214]
### Description of feature

Cellranger requires the fastq files to follow a specific pattern. It would be nice to have the pipeline taking care of renaming the files.
One possibility would be to create a symlink for each file with the required pattern using regex.

**Comment by grst** [comment]
See also https://github.com/nf-core/scrnaseq/issues/147, https://github.com/nf-core/scrnaseq/issues/195
