### ISSUE TITLE
Extend Pipeline to analyze CAR-T-cell datasets

### ISSUE THREAD

**Issue by Karantea** [nf-core/scrnaseq#236]
Hello, 

my name is Josefine and I am working on my master thesis in cooperation with the Fraunhofer IZI in Leipzig. We aim to use the scrnaseq-pipeline to analyze single-cell-sequencing datasets in the context of CAR-T-cells which are genetically modified immune cells targeting specific cancer cells. We would like to extend your existing pipeline with scripts and parameters regarding this issue which I can explain more in detail if you want me to.

I wanted to get in touch with you before we start with developing an enhancement to check if you would be interested in this although it is a very specific one for limited use cases and a small target group.

Best regards,
Josefine Selke

**Comment by grst** [comment]
Hi Joesefine, 

would be great if you could explain in a bit more detail what these extra steps are and at what point of the pipeline they need to run. 

In general, this sounds like a rather specific analysis of which I'm not sure we'd want to support in this workflow, as we are already struggeling to maintain the current core functionality at an adequate level.
