### ISSUE TITLE
Segmentation fault caused by bustools_correct_sort

### ISSUE THREAD

**Issue by galanisl** [nf-core/scrnaseq#24]
I'm facing this issue when trying to align with `kallisto`:

```
Error executing process > 'bustools_correct_sort (E9_5_extraembryonic_bus_output)'

Caused by:
  Process `bustools_correct_sort (E9_5_extraembryonic_bus_output)` terminated with an error exit status (139)

Command executed:

  bustools correct -w 10x_V3_barcode_whitelist -o E9_5_extraembryonic_bus_output/output.corrected.bus E9_5_extraembryonic_bus_output/output.bus    
  mkdir -p tmp
  bustools sort -T tmp/ -t 8 -m 64G -o E9_5_extraembryonic_bus_output/output.corrected.sort.bus E9_5_extraembryonic_bus_output/output.corrected.bus

Command exit status:
  139

Command output:
  (empty)

Command error:
  Found 6794880 barcodes in the whitelist
  Processed 0 bus records
  In whitelist = 0
  Corrected = 0
  Uncorrected = 0
  Read in 0 BUS records
  .command.sh: line 4: 16827 Segmentation fault      bustools sort -T tmp/ -t 8 -m 64G -o E9_5_extraembryonic_bus_output/output.corrected.sort.bus E9_5_extraembryonic_bus_output/output.corrected.bus
```

It seems that bustools is a memory intensive task, so this issue could be solved by allowing the user to set parameter `-m`.

I've attached the associated log file.
[nextflow.log](https://github.com/nf-core/scrnaseq/files/4185641/nextflow.log)

**Comment by apeltzer** [comment]
I double checked this behaviour and cannot further adjust this atm - we already use the `-m` parameter and set the value to whatever the profile specifies when running the process (depending on the host system / profile configuration for that task.) See: https://github.com/nf-core/scrnaseq/blob/884e541285330e1ef4771ff9267ce27e42dfb2e3/main.nf#L639

Not sure we can further improve that, I'm wondering whether this is the real reason 🤔

**Comment by galanisl** [comment]
I noticed that the intermediate output.bus files generated by kallisto were empty (see `Read in 0 BUS records above`) and this causes the segmentation fault in the `bustools sort` step. My fastq files had the following permissions:

`u=rwx,g=,o=`

Changing them to `u=rwx,g=rx,o=r` solved the problem in my HPC environment.
