### ISSUE TITLE
Support for 10x FFPE scRNA

### ISSUE THREAD

**Issue by pakiessling** [nf-core/scrnaseq#247]
### Description of feature

Hi,
unsure if this is supported yet.
10x offers new kits to process scRNA from FFPE https://www.10xgenomics.com/products/single-cell-gene-expression-flex
The data is processed with `cellranger multi` https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/multi
It would be really cool to have this as part of the pipeline!

**Comment by grst** [comment]
related discussion for adding `cellranger multi`: 
https://github.com/nf-core/scrnaseq/issues/174

The `cellranger multi` module on `nf-core/modules` has been merged: 
https://github.com/nf-core/modules/pull/3229

**Comment by pakiessling** [comment]
@grst  Cool. Does that mean I can use it in nf-core/scrnaseq yet or does the module still need to be incoperated?

**Comment by grst** [comment]
No, this still needs to be implemented here. I was just linking the issues for reference.

**Comment by fmalmeida** [comment]
Hi @grst ,
Should this ticket now be closed?

**Comment by grst** [comment]
Yes, this is now available with cellranger multi
