### ISSUE TITLE
Failed to pull singularity image

### ISSUE THREAD

**Issue by Juassis** [nf-core/scrnaseq#248]
### Description of the bug

Hej,
I just updated the scrnaseq and I get the singularity error message. I know I can run with docker and it will work. But I wanna report the singularity error message.

I tried to fix by myself, but I could't find the right missing image.

`nextflow run nf-core/scrnaseq -profile test,singularity --outdir test`

**ERROR ~ Error executing process > 'NFCORE_SCRNASEQ:SCRNASEQ:MTX_CONVERSION:MTX_TO_SEURAT (1)'**

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name nf-core-seurat-4.3.0.img.pulling.1688553475471 docker://nf-core/seurat:4.3.0 > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://nf-core/seurat:4.3.0: reading manifest 4.3.0 in docker.io/nf-core/seurat: errors:
    denied: requested access to the resource is denied
    unauthorized: authentication required

 -- Check '.nextflow.log' file for details

### Command used and terminal output

```console
`nextflow run nf-core/scrnaseq -profile test,singularity --outdir test`
```

**Comment by grst** [comment]
Should be fixed by https://github.com/nf-core/scrnaseq/pull/245 which includes the configuration for setting quay.io as default singularity registry. 

https://github.com/nf-core/scrnaseq/pull/245/files#diff-ce7465a8e67b3b9c95696db1146ca7e6328f075e08a3d64062b87aa8608fc4eaR210-R213

**Comment by Juassis** [comment]
Perfect!

**Comment by denisthieffry** [comment]
I got to the same issue, while testing the  nf-core/scrnaseq v2.3.2-g06a85e8 on the 10x 1k human PBMCs data set (human healthy donor, v3 chemistry). 
Do we have to wait that the template update for nf-core/tools v2.9 be done or is it possible to call a different version of nf-core tools with the current scRNAseq pipeline?

**Comment by denisthieffry** [comment]
I found out how to run the pipeline's dev branch, for which the fix has been pulled, by adding  "-revision 0e5fc8b" in the command line.

**Comment by apeltzer** [comment]
`-r dev`would work too ;-)

**Comment by grst** [comment]
As the fix is on the latest release, I'm closing this issue.
