### ISSUE TITLE
Incorrect name of Alevin option in docs

### ISSUE THREAD

**Issue by galanisl** [nf-core/scrnaseq#25]
According to [the docs](https://nf-co.re/scrnaseq/docs/usage#alevin), the parameter that allows the specification of a transcript to gene mapping file for Salmon Alevin and AlevinQC is `--txp2gene_alevin` but it should be `--txp2gene` (see [main.nf](https://github.com/nf-core/scrnaseq/blob/master/main.nf)).

**Comment by apeltzer** [comment]
See https://github.com/nf-core/scrnaseq/pull/26 for small fix

**Comment by grst** [comment]
that PR was merged, so I guess we can close this.
