### ISSUE TITLE
Autorenaming of files in new cellranger module leads to erroneous renaming of sample ID containing R1 in it, like in SRR ids

### ISSUE THREAD

**Issue by BurtonChia** [nf-core/scrnaseq#265]
### Description of the bug

When running scrnaseq v 2.4.0 with the new cellranger  #246  , we are encountering errors like this. This happens on all samples starting with SRR1xxx.

```
AssertionError: We expect R1 and R2 of the same sample to have the same filename except for R1/R2.
  Files involved:
      - fastq_001/SRR14923965_S1_L001_R1_001.fastq.gz
      - fastq_002/SRR14923965_S1_L001_R2_001.fastq.gz
```

A look at the command indicates the error is due to how the renaming of r1.name for the comparison for r2.name, in particular:
`if r1.name.replace("R1", "R2") != r2.name:`

Instead, this line should read: `if r1.name.replace("_R1_", "_R2_") != r2.name:` to ensure sample IDs containing "R1" in them don't get renamed by mistake.

**Comment by grst** [comment]
Thanks for reporting, this should already be fixed on `dev`
See https://github.com/nf-core/scrnaseq/pull/261

Would be great if you could give it a try!

**Comment by BurtonChia** [comment]
That's great! We'll give the dev build a run and report back the results.
