### ISSUE TITLE
Problems with alevin's tx2gene mapping generation

### ISSUE THREAD

**Issue by galanisl** [nf-core/scrnaseq#27]
The method used by the pipeline to generate the transcript to gene mapping file for alevin relies on specific positions of the GTF's attributes column. This means that if the order of attributes changes (as it is the case in Gencode vs Ensembl GTFs), the mapping file will be invalid.

It is possible to generate a valid mapping file for virtually any GTF using [this script](https://github.com/BUStools/getting_started/releases/download/getting_started/t2g.py) and skipping gene names. Then, one should be able to use option `--txp2gene` with the path to the valid file. However, it seems that even when the option is set to the file path, the pipeline generates its own, potentially invalid, mapping file. If the file is invalid, it can be substituted by the valid one in the appropriate directory under `./work`.

One possible solution is to use the above python script to generate the mapping file, as it is already part of the pipeline.

**Comment by apeltzer** [comment]
Thanks for opening the issue here - this is not correct at the moment and we should fix this.

**Comment by grst** [comment]
I belive this issue was created when we were still using an `awk` command to generate the t2g file for alevin (see #23). Can this be closed now that we are using `gffread` for that? 

Or is there still an advantage of using `t2g.py` for alevin?

**Comment by apeltzer** [comment]
Please try out 2.0.0 - which was just released and reopen an issue if the problem persists 👍🏻
