### ISSUE TITLE
Bump up kb to 0.28.0

### ISSUE THREAD

**Issue by gennadyFauna** [nf-core/scrnaseq#280]
### Description of feature

The new version of kallisto|bustools is out (https://www.biorxiv.org/content/10.1101/2023.11.21.568164v1): kb is at 0.28.0, breaking compatibility with the old versions. The `nucleus` and `lamanno` workflows have been superseded by `nac`, which separately quantifies nascent, mature, and ambiguous transcripts. In addition, `kb count` now accepts an optional `sum` argument, which adds matrices together to match common workflows. 

It would be good to move nf-core/scrnaseq to the newest version. I would appreciate help; the right way to combine the `sum` variable and the h5ad generation is not obvious to me.

**Comment by grst** [comment]
Hi @gennadyFauna, 

thanks for the heads-up, I'm all for updating this! 

> I would appreciate help; the right way to combine the sum variable and the h5ad generation is not obvious to me.

I suggest to first bump the version of kb in [nf-core/modules](https://github.com/nf-core/modules/). Then make a PR to scrnaseq updating the module and we'll see what exactly breaks.

**Comment by Yenaled** [comment]
@gennadyFauna -- I am an author on the preprint. Latest version of kb is 0.28.2; deff update to that if you can!

For standard workflow, commands are the same as before.

For the nac index type, --sum=total should be used and the resulting cells_x_genes.total.mtx matrix will give you the CellRanger7-like quantification (i.e. introns are counted) whereas the cells_x_genes.cell.mtx matrix will give you the kb standard workflow quantifications which are essentially the CellRanger3-like quantification (i.e. introns not counted).

For single-cell RNA velocity type analysis, use cells_x_genes.cell.mtx for your "spliced" matrix and cells_x_genes.nascent.mtx for your "unspliced" matrix.

Side note: You can also use kb-python for bulk RNAseq (so might be worth updating the bulk RNAseq pipelines for that as well ;) -- the abundance.tsv output will be the same as before and can be thrown into DE programs).

**Comment by grst** [comment]
#294 has been merged in dev and will be part of the next release.
