### ISSUE TITLE
The cellrangerarc cannot start successfully

### ISSUE THREAD

**Issue by wzheng0520** [nf-core/scrnaseq#297]
### Description of the bug

Based on newest update on the pipeline, I am using `--aligner cellrangerarc` to perform my analyzing for 10X multiome GEX+10X multiome ATAC. However, the pipeline cannot started successfully and provide the following error message ERROR ~ Cannot invoke method `containsKey()` on null object . I review the code and found this error might cause by `protocol_config = WorkflowScrnaseq.getProtocol(workflow, log, params.aligner, params.protocol)` which is located in the [scrnaseq.nf](https://github.com/nf-core/scrnaseq/blob/master/workflows/scrnaseq.nf) at line 73. Therefore, I went to [protocols.json](https://github.com/nf-core/scrnaseq/blob/master/assets/protocols.json) files which is located at assets folder and found there is **no cellrangerarc** in there. From my understanding, in the getProtocol function, the aligner cannot be find through the json files and the error shows up.

Also on the line 74 to 75 in [scrnaseq.nf](https://github.com/nf-core/scrnaseq/blob/master/workflows/scrnaseq.nf), 
```
if (protocol_config['protocol'] == 'auto' && params.aligner != "cellranger") {
    error "Only cellranger supports `protocol = 'auto'`. Please specify the protocol manually!"
}
```
looks like it only allow the `cellranger` to choose auto, however, from my understanding, the `cellrangerarc` should be the same, maybe it is good to add `params.aligner != "cellrangerarc"` also on here. 

### Command used and terminal output

```console
ERROR ~ Cannot invoke method `containsKey()` on null object
```

### System information

N E X T F L O W  ~  version 23.10.0
 nf-core/scrnaseq 2.5.1

**Comment by heylf** [comment]
Should be fixed with this [PR](https://github.com/nf-core/scrnaseq/pull/300/files#diff-1b4d9315e66b5c91a661df38866c6b1371117f443c1ada9d1a41b1cdcda2944a)

**Comment by grst** [comment]
Fixed in `dev`
