### ISSUE TITLE
Issues with samplesheet.csv as well as additional columns in the samplesheet

### ISSUE THREAD

**Issue by SethMagnusJarvis** [nf-core/scrnaseq#303]
### Description of the bug

I tried running the pipeline using the samplesheet and it gave me an error complaining about the number of column names. This disappeared when I remove the sample columns. 

According to this post on slack, this apparently shouldn't be an issue "https://nfcore.slack.com/archives/CHN5BV5DW/p1679325616556869"

Either way, the samplesheet should probably be edited so it works.

### Command used and terminal output

```console
nextflow run nf-core/scrnaseq --input ./samplesheet.csv --outdir /rds/general/user/user/home/test_results/scrna --genome GRCh38 -profile imperial, standard --aligner cellranger
```

**Comment by muharif** [comment]
Hi Seth, I am experiencing the same problem. How did you solve it? I tried to remove the sample column, but it is still showing the same error.

Thanks!

**Comment by SethMagnusJarvis** [comment]
@muharif The sample sheet had 5 columns, I had to remove everything that wasn't sample,fastq_1,fastq_2. I haven't got the pipeline working, but the error changed so I think it resolved it.

**Comment by grst** [comment]
Hi, 

this issue should be fixed in the development version. 
You can give it a try with `nextflow run ... -r dev`. If it doesn't work, please let me know!
