### ISSUE TITLE
Samplesheet Check Bug

### ISSUE THREAD

**Issue by pablasimarjot** [nf-core/scrnaseq#304]
### Description of the bug

I am getting this error while running the pipeline in the samplesheet check:
ERROR: Please check samplesheet header -> ﻿sample,fastq_1,fastq_2 != sample,fastq_1,fastq_2

The samplesheet.csv header matches the requirement, yet it fails the check. 

### Relevant files

[nf-log.log](https://github.com/nf-core/scrnaseq/files/14214448/nf-log.log)

**Comment by grst** [comment]
Hi, 

this issue should be fixed in the development version. 
You can give it a try with `nextflow run ... -r dev`. If it doesn't work, please let me know!
