### ISSUE TITLE
Use compressed (gzip) fasta and gtf

### ISSUE THREAD

**Issue by zeehio** [nf-core/scrnaseq#314]
### Description of feature

It would be nice if the scrnaseq pipeline had a similar/compatible genome preparation as the rnaseq pipeline.

I guess we all lack the time to port and implement it avoiding deduplication.

See:

https://github.com/nf-core/rnaseq/blob/master/subworkflows/local/prepare_genome/main.nf

**Comment by grst** [comment]
Duplicate of #313

**Comment by grst** [comment]
Yeah, we should have this here... Do you want to make a PR?

**Comment by grst** [comment]
It's actually already implemented in #276. Will be fixed once this gets merged.
