### ISSUE TITLE
allow for extra columns in the sample sheet

### ISSUE THREAD

**Issue by nick-youngblut** [nf-core/scrnaseq#323]
### Description of feature

[check_samplesheet.py](https://github.com/nf-core/scrnaseq/blob/master/bin/check_samplesheet.py) currently requires the input sample sheet to only include specific columns:

```
        MIN_HEADER = ["sample", "fastq_1", "fastq_2"]
        OPT_HEADER = ["expected_cells", "seq_center", "fastq_barcode", "sample_type"]
```

There's no need to prevent extra columns, given that they can simply be ignored. 

Allowing for extra columns enables the user to include extra metadata in the sample sheet, if they choose.

In my specific case, I could not use: `ngs_run,sample,fastq_1,fastq_2`, which generated the error:

```console
ERROR: Please check samplesheet header -> ngs_run,sample,fastq_1,fastq_2 != sample,fastq_1,fastq_2
```

...since `ngs_run` is not an allowed header.

**Comment by grst** [comment]
This should already be fixed in the development version and in the upcoming 2.6.0 release.
