### ISSUE TITLE
Channel 'star_index' used twice

### ISSUE THREAD

**Issue by ChillyMomo709** [nf-core/scrnaseq#33]
Hi,

I ran the following using the star_index of the testdata (made by default run settings of STAR genomeGenerate) 

`nextflow run nf-core/scrnaseq --reads 'data/S10_L001/*_R{1,2}*.fastq.gz' -profile docker -r 1.0.0 --aligner star --type 10x --chemistry V3 --fasta data/references/GRCm38.p6.genome.chr19/GRCm38.p6.genome.chr19.fa --gtf data/references/GRCm38.p6.genome.chr19/gencode.vM19.annotation.chr19.gtf --max_memory 6.GB --max_cpus 2 --star_index data/references/GRCm38.p6.genome.chr19/star/`

I get the following error:

`Channel `star_index` has been used twice as an output by process `makeSTARindex` and another operator

 -- Check script '/root/.nextflow/assets/nf-core/scrnaseq/main.nf' at line: 365 or see '.nextflow.log' file for more details`

Information output:
N E X T F L O W  ~  version 20.01.0
Launching `nf-core/scrnaseq` [insane_watson] - revision: 884e541285 [1.0.0]
[2m----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/scrnaseq v1.0.0
----------------------------------------------------
Pipeline Release  : 1.0.0
Run Name          : insane_watson
Reads             : data/S10_L001/*_R{1,2}*.fastq.gz
Genome Reference  : data/references/GRCm38.p6.genome.chr19/GRCm38.p6.genome.chr19.fa
GTF Reference     : data/references/GRCm38.p6.genome.chr19/gencode.vM19.annotation.chr19.gtf
Save Reference?   : false
Aligner           : star
STARsolo Index    : data/references/GRCm38.p6.genome.chr19/star/
Droplet Technology: 10x
Chemistry Version : V3
Max Resources     : 6.GB memory, 2 cpus, 10d time per job
Container         : docker - nfcore/scrnaseq:1.0.0

Shouldn't  'makeSTARindex' be switched off when using a star_index?

Best,
Momo

**Comment by apeltzer** [comment]
It should - I fear I have to really sit down with this pipeline a couple of times more to fix some of the issues we have. Currently quite swamped with other things unfortunately, so if someone wants to have a go :-)

**Comment by tthyer** [comment]
+1 I also encountered this error

**Comment by chaochungkuo** [comment]
Same here.

**Comment by apeltzer** [comment]
The DSLv2 rewrite is almost ready -- please have a look at the `dsl2` branch of this pipeline that should cover a large portion of  the pipeline updates and also ffix this 👍🏻

**Comment by apeltzer** [comment]
Fixed in `dev`
