### ISSUE TITLE
Specify cellranger version

### ISSUE THREAD

**Issue by maggiebr0wn** [nf-core/scrnaseq#338]
Hello, I wanted to know if there was a way to specify the cellranger version used. For single cell analyses, using different versions of cellranger can affect the data, and for projects with multiple batches, we'd like to keep using the same cellranger version even if it gets updated. Also, is it possible to change cellranger parameters (for instance, include or exclude introns). Thanks!

**Comment by grst** [comment]
This would be possible using custom nextflow configuration files, see here: https://nf-co.re/docs/usage/getting_started/configuration#customising-tool-arguments

It is also possible to override the used container version the same way, however there's no guarantee that the pipeline is still compatible with that particular cellranger version.
