### ISSUE TITLE
Question: STAR version 2.7.3a

### ISSUE THREAD

**Issue by MomoMiddel** [nf-core/scrnaseq#34]
It says in environment.yml that version 2.7.3a is broken and therefore version 2.7.2c is used. I was wondering how you checked that 2.7.3a is broken. 

Thanks!
Momo

**Comment by apeltzer** [comment]
It simply crashed all our continous integration tests whenever we tried bumping to 2.7.3a - gave up after a while then looking into whats the reason for it, but random core dumps / segfaults happened very often.
