### ISSUE TITLE
nextflow inspect does not work due to missing parameters

### ISSUE THREAD

**Issue by stevekm** [nf-core/scrnaseq#347]
### Description of the bug

I am trying to programmatically get the list of all containers in the pipeline. However the standard command `nextflow inspect` does not seem to work, even if you tell it to ignore errors.

```
nextflow inspect "https://github.com/nf-core/scrnaseq" -r "master" -ignore-errors
ERROR ~ ERROR: Validation of pipeline parameters failed!


The following invalid input values have been detected:

* Missing required parameter: --input
* Missing required parameter: --outdir
```

Any ideas how to fix this? Ideally in a manner that will work for all pipelines, and not just `scrnaseq`, since I will be using the same method to get the list of containers from all pipelines running in the Nextflow Tower instance.

@robsyme you might be interested in this one also

### System information

nextflow version 24.04.2.5914

**Comment by robsyme** [comment]
I'd recommend adding `-profile test,docker`. This will solve at least the `--input` parameter and will ensure that `nextflow inspect` returns you docker images. This is the default, but there is no harm in being explicit.

Almost all nf-core workflows will only then require `--outdir` which you can set to an arbitrary directory that can be deleted afterwards.

**Comment by robsyme** [comment]
What is the `ignore-errors` parameters - I don't think I've seen that before.

**Comment by grst** [comment]
I don't think there's anything to fix in scrnaseq for now. Either `inspect` needs to be improved, or the nf-core template.
