### ISSUE TITLE
Support for 10x Gem-X V4 libraries

### ISSUE THREAD

**Issue by divyanshusrivastava** [nf-core/scrnaseq#349]
### Description of feature

Current version of the pipelien (v2.7.0) runs Cellranger v7, however cellranger v8 is required to process libraries prepared with 10x Gem-X V4 protocol. 

Requesting the developers to have cellranger v8 support. 
Thanks

**Comment by grst** [comment]
Should be v8 already, see here: 
https://github.com/nf-core/scrnaseq/blob/c8f02f515d014ee2c98b401950e2cf7141a82b42/modules/nf-core/cellranger/count/main.nf#L5

@nick-youngblut is working on 10xV4 support in https://github.com/nf-core/scrnaseq/pull/348

**Comment by grst** [comment]
The changes from #348 have been merged. Could you give it a try if you can run the pipeline on your data with the `dev` version?

**Comment by nick-youngblut** [comment]
@grst I don't see any docs on `SC5P-PE-v3` and `SC5P-R2-v3` (CellRanger). Are they currently supported?

**Comment by grst** [comment]
I would expect that when you specify `auto`, cellranger would auto-detect the chemistries and run through. Would be great to test that + explicitly add them to the supported protocols though.

**Comment by divyanshusrivastava** [comment]
Thanks all, it worked for me with the latest pipeline version already. Did not try the dev. 
From my end, the issue can be closed !
