### ISSUE TITLE
test_full-profile not running out-of-the-box

### ISSUE THREAD

**Issue by asp8200** [nf-core/scrnaseq#366]
### Description of the bug

The `test_full`-profile doesn’t run out-of-the-box on scrnaseq v.2.7.1:
```
nextflow run nf-core/scrnaseq -r 2.7.1 -profile test_full,singularity --outdir results
...
ERROR ~ Must provide a genome fasta file ('--fasta') and a gtf file ('--gtf') if no index is given!. Expression: (star_index || (genome_fasta && gtf)). Values: star_index = [], genome_fasta = [], gtf = []
```
So I added `--genome GRCh38`, but it still didn’t work.

Then I removed the initialisation of `fasta` and `gtf` from `nextflow.config` which was introduced [here](https://github.com/nf-core/scrnaseq/blob/4171377f40d629d43d4ca71654a7ea06e5619a09/nextflow.config#L22-L23) in v2.7.1.

And the `test_full`-profil ran OK.

Having removed the initialisation of `fasta` and `gtf`, I got the following warnings which are also kind of misleading, since, in this case, `fasta` and `gtf` are being set through `igenomes.config`:
```
WARN: Access to undefined parameter `gtf` -- Initialise it to a default value eg. `params.gtf = some_value`
WARN: Access to undefined parameter `fasta` -- Initialise it to a default value eg. `params.fasta = some_value`
```

Issue first report on Slack [here](https://nfcore.slack.com/archives/CHN5BV5DW/p1725266961823989).

**Comment by wzheng0520** [comment]
Hi @asp8200 I also meet same issue and I think it cause by `params.fasta = getGenomeAttribute('fasta')` and `params.gtf = getGenomeAttribute('gtf')` update in scrnaseq.nf cannot be accepted. Once you defined them on nextflow.config as `null`, any updated in workflow cannot really make them to be updated into correct path.

**Comment by fmalmeida** [comment]
Hi @wzheng0520 ,
That is the correct problem. I am also have come under this error and worked on a fix as well in #369 
There I am being able to run the test full profile correctly.
So maybe we can bring the changes to your branch once that one gets merged.

So, @asp8200, thanks for reporting and this will hopefully get fixed with #369

**Comment by grst** [comment]
This should be fixed in dev now. Would be great if you could give it a try and let us know if there are still any issues!

**Comment by asp8200** [comment]
I've just kickoff a run of the `test_full`-profile on the `dev`-branch. Will report back when done.
