### ISSUE TITLE
MTX_TO_H5AD module cannot take ch_star_index

### ISSUE THREAD

**Issue by wzheng0520** [nf-core/scrnaseq#370]
### Description of the bug

Hi,

Thanks for upgrading this pipeline into newer version, I think here is a issue I meet after upgrading. I found it might cause by `ch_star_index` code is updated from `ch_star_index = params.star_index ? file(params.star_index) : []` into  `ch_star_index = star_index ? [[id: star_index.baseName], star_index] : []`. It causes the ch_star_index changed into linked list stared with `star_index.baseName`. However, in MTX_TO_H5AD module, their input still take `path star_index`. 

From my understanding, `path star_index` cannot accept the new `ch_star_index` format and we might need to either change the input formate for star_index into acceptable way or we might can directly use ` star_index = params.star_index ? file(params.star_index, checkIfExists: true) : null ` as input for MTX_TO_H5AD. 

like this:
```
MTX_CONVERSION (
        ch_mtx_matrices,
        ch_input,
        ch_txp2gene,
        star_index
    )
```

### Command used and terminal output

```console
Error executing process > 'NFCORE_SCRNASEQ:SCRNASEQ:MTX_CONVERSION:MTX_TO_H5AD (1)'

Caused by:
  Not a valid path value type: java.util.LinkedHashMap ([id:STARIndex])


Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

**Comment by grst** [comment]
We are currently refactoring the matrix conversion code in #369. This should hopefully also fix the error you are encountering.

**Comment by wzheng0520** [comment]
Thanks so much!

**Comment by grst** [comment]
This should be fixed in dev now. Would be great if you could give it a try and let us know if there are still any issues!
