### ISSUE TITLE
Allow pre-built cellranger index, CellrangerARC index, simpleaf Index, and simpleaf tx2pgene load from igenomes.json

### ISSUE THREAD

**Issue by wzheng0520** [nf-core/scrnaseq#371]
### Description of feature

Hi guys,

Right now, I found for cellranger index, simpleaf index and simpleaf tx2pgene, the only way we can provide the pre-built indices is through using `--cellranger_index`, `--salmon_index` and `--txp2gene` parameters. I am thinking about if we already have the default path of those pre-built indices, once we use our own igenomes.config file, those indices should be directly pull from there like `fasta`, `gtf`, or `star_index` right now in the pipeline. 

I think if it is possible to add following lines before we defined their channel in the `scrnaseq.nf`
```
params.salmon_index = getGenomeAttribute('simpleaf')
params.txp2gene = getGenomeAttribute('simpleaf_tx2pgene')
params.cellranger_index = getGenomeAttribute('cellranger')
```
to allow the pipeline can capture the those information directly from  `igenomes.config` if the `--genome` we provided have those information. 

Sincerely
Winnie Zheng

**Comment by FelixKrueger** [comment]
I would like to second this. It doesn't make sense to re-run all indexing processes for every single run when they are already part of the genome config file. This should also be cut down noticeably the execution time, and the carbon footprint!

**Comment by FelixKrueger** [comment]
Tagging @apeltzer. This would be good to add, I believe we've got this internally already.

**Comment by FelixKrueger** [comment]
I have opened a PR for this (see link above), I think we can close this issue.

**Comment by maciekmigdal** [comment]
Hi, I am having exactly the same need as the OP. Unfortunately, I found that #469 removed the changes implemented by @FelixKrueger, and I would ask to re-open this issue. Based on this [comment](https://github.com/nf-core/scrnaseq/pull/469/changes#r2115915944) it seems it was removed without considering this issue. @nictru @fmalmeida could you please have a look. Is there some other way to support cellranger index when using custom/own igenomes.json? The documentation mentions [refgenie](https://nf-co.re/docs/usage/reference_genomes#using-refgenie-for-genome-management) as a reference source, but I guess it works through the same mechanism and won't support cellranger index either?

**Comment by fmalmeida** [comment]
Hi @nictru was this checked when doing the PR mentioned?

I actually think that was in purpose, that the idea was that custom indexes were only given by the custom parameters. Right?

If not, I think it would not harm if we can re-allow it to define via custom igenome JSONs.

Any strong opposition? @grst any opinions?


@maciekmigdal if you have a branch that we could open a PR from, feel free to open and tag us.

Otherwise, I can take a look after Easter 🙂

**Comment by fmalmeida** [comment]
@maciekmigdal ,
If you open a new issue referring this one, then I think it should be easier to track, continue discussions.
