### ISSUE TITLE
bustools runs out of memory

### ISSUE THREAD

**Issue by dangeles** [nf-core/scrnaseq#38]
When running in `kallisto mode`, the pipeline fails at the `bustools sort` step.

I think the problem is a bug with `bustools`. If I replace the memory allocated to `bustools` (set via `config.base`) with a hard-coded memory slightly less than the `config.base` memory, the pipeline runs without issues.

**Comment by apeltzer** [comment]
Do you want to contribute a PR fixing this? I might have a go myself but almost in vacation now so can't promise that I find the time to fix this these days (... and doing most of nf-core stuff now in my spare time too)

**Comment by grst** [comment]
Closing this, as the issue is quite old and kallisto has been refactored into a DSL2 module since, which very likely fixes the issue. 
Anyone, feel free to open a new issue if the problem persists.
