### ISSUE TITLE
cellranger-multi => create-bam option

### ISSUE THREAD

**Issue by nick-youngblut** [nf-core/scrnaseq#384]
### Description of feature

As stated in the [10X docs](https://www.10xgenomics.com/support/software/cell-ranger/latest/analysis/running-pipelines/cr-flex-multi-frp): 

> Important: In the examples below, we set create-bam to "false" so Cell Ranger will not generate a BAM file. This setting is recommended for Fixed RNA Profiling libraries and will reduce both the total computation time for the pipestance and the size of the output directory.

It appears that there is currently no way of setting `create-bam` to true/false via the scrnaseq pipeline params.

**Comment by kopichris** [comment]
I would like to have this added as well.  Happy to open a pull request for this @nick-youngblut if you don't have any objections!

**Comment by grst** [comment]
@kopichris, happy to accept such a PR

**Comment by nick-youngblut** [comment]
@kopichris that sounds great! I could also possibly add it, but I probably couldn't get to it for a few days.

**Comment by kopichris** [comment]
> [@kopichris](https://github.com/kopichris) that sounds great! I could also possibly add it, but I probably couldn't get to it for a few days.

@nick-youngblut I would love the opportunity to make my first pull request if possible :D!
