### ISSUE TITLE
MTX_CONVERSION:MTX_TO_SEURAT fails with certain feature names

### ISSUE THREAD

**Issue by ChristopherBarrington** [nf-core/scrnaseq#385]
### Description of the bug

When using `--aligner cellranger` the matrix files are not read correctly by `ReadMtx` but are read correctly by `Read10X`.

```
Command error:
  Attaching SeuratObject
  Error: Matrix has 13931 rows but found 12861 features.
  In addition: Warning messages:
  1: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
    EOF within quoted string
  2: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
    number of items read is not a multiple of the number of columns
  Execution halted
```

The 12861st feature is:

```
FBgn0025724     beta'COP        Gene Expression
```

It looks like the `read.table` function used by `ReadMtx` causes the problem - only reading so far as this feature. The `Read10X` function uses `read.delim` which uses the string as-is. Maybe `Read10X` would be a more robust alternative, assuming all aligners output in the 10X format?

### System information

* quay.io-nf-core-seurat-4.3.0.img
* nf-core/scrnaseq@2.7.1

**Comment by grst** [comment]
Hi @ChristopherBarrington, 

thanks for reporting! The whole conversion workflow will be reimplemented in https://github.com/nf-core/scrnaseq/pull/369 hopefully fixing also this issue.

**Comment by ChristopherBarrington** [comment]
ok thanks, in the interim I have used a custom config to ignore if an error occurs

```
process {
	withName: 'NFCORE_SCRNASEQ:SCRNASEQ:MTX_CONVERSION:MTX_TO_(H5AD|SEURAT)' {
		errorStrategy = 'ignore'
	}
}
```

**Comment by grst** [comment]
This should be fixed in dev now. Would be great if you could give it a try and let us know if there are still any issues!
