### ISSUE TITLE
alevinQC -- pandoc-citeproc is not available

### ISSUE THREAD

**Issue by Thatguy027** [nf-core/scrnaseq#39]
Hello,

I am trying to get the test profile up and running and came across the following error:

Ran this:
`nextflow run nf-core/scrnaseq -profile test`

Error:
```
Command error:
  Loading required package: alevinQC
  Registered S3 method overwritten by 'GGally':
    method from   
    +.gg   ggplot2
  Loading required package: tximport
  Error in .checkPandoc(ignorePandoc) : pandoc-citeproc is not available!
  Calls: alevinQCReport -> .checkPandoc
  Execution halted
```

Not really sure what to make of this error, but was hoping you might have some insight.

**Comment by apeltzer** [comment]
Not sure either - probably will need to add this as a dependency in the `environment.yaml` for the next maintenance release

**Comment by apeltzer** [comment]
Can you run with `-profile test,docker` or `-profile test,singularity` or `-profile test,conda` ?

**Comment by grst** [comment]
Should be fixed in the dsl2 version in dev.
