### ISSUE TITLE
Option to use cellranger pre-built reference

### ISSUE THREAD

**Issue by svigneau** [nf-core/scrnaseq#399]
### Description of feature

It would save time and computing resources if the pipeline could take cellranger pre-built references (downloadable [here](https://www.10xgenomics.com/support/software/cell-ranger/downloads#reference-downloads)) instead of rebuilding them from FASTA and GTF files when using the `cellranger` or `cellrangermulti` aligner parameter.

**Comment by grst** [comment]
This should be fixed on `dev`, could you give it a try?

**Comment by svigneau** [comment]
Thanks for pointing this out!

I tried the following, which ran out fine:

1. Download a pre-built `cellranger` reference  from this [page](https://www.10xgenomics.com/support/software/cell-ranger/downloads#download-links) using:
```
curl -O "https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2024-A.tar.gz"
tar -xzf refdata-gex-GRCh38-2024-A.tar.gz
```
2. Modify the `conf/igenomes.config` file by adding the following genome:
```
'GRCh38-2024-A' {
     cellranger = '/path/to/refdata-gex-GRCh38-2024-A/'
 }
```
3. Add the following line to my `params.yaml` file:
```
genome: 'GRCh38-2024-A'
```
4. Run with:
```
nextflow run /path/to/scrnaseq/main.nf -params-file params.yaml -c nextflow.config
```

It feels a bit odd having to modify the pre-defined `igenomes.config` file, though, instead of being able to pass a custom `genomes.config` file. What do you think about adding this functionality?

**Comment by grst** [comment]
Hi @svigneau, 

the intended way to provide cellranger references would be via the `--cellranger_index` parameter. 
It should also already be possible to override the genomes configuration in a custom config file and specify it with `-c`. Did you try that?

**Comment by svigneau** [comment]
Thanks for the follow-up!

I tried both options and both worked :)

Here is what I did for reference:
- Using the `cellranger_index` parameter:
  - Add `cellranger_index: '/path/to/refdata-gex-GRCh38-2024-A/'` to the`params.yaml` file
  - Run locally with `nextflow run /path/to/nf-core/scrnaseq/main.nf -params-file params.yaml -c nextflow.config`
- Using a `cellranger-genomes.config` file:
  - Create a `cellranger-genomes.config` file containing:
    ```
    params {
        genomes {
            'GRCh38-2024-A' {
                cellranger = 'gs://svigneau-b2/references/refdata-gex-GRCh38-2024-A/'
            }
        }
    }
    ```
  - Add `genome: 'GRCh38-2024-A'` to the `params.yaml` file
  - Run locally with `nextflow run /path/to/nf-core/scrnaseq/main.nf -params-file params.yaml -c nextflow.config -c cellranger-genomes.config`
