### ISSUE TITLE
Make output compatible with nf-core/scflow

### ISSUE THREAD

**Issue by apeltzer** [nf-core/scrnaseq#66]
# nf-core/scrnaseq feature request

## Describe the solution you'd like

Would be great to generate (extra?) output for the nf-core/scflow pipeline that allows using the output matrices from this pipeline directly in the scflow pipeline as input 👍🏻  @combiz and I discussed that a bit in the #scflow channel on slack. 

Would require some bits added, but shouldn't be too much extra effort and would enable direct downstream analysis for quite some projects - which would benefit both the scrnaseq users and scflow users ;-)

**Comment by grst** [comment]
scflow seems pretty rather dead and there hasn't been a lot of interest in this issue. Closing for now - If someone thinks differently, feel free to reopen.
