### ISSUE TITLE
Add AnnData output process

### ISSUE THREAD

**Issue by Zethson** [nf-core/scrnaseq#68]
Ahoy pirates,

sister issue for https://github.com/theislab/sfaira/issues/392
We would suggest to add a process to output an AnnData object. This would allow us to add new fields to Sfaira dataloaders to indicate how the raw data was processed. Detailed discussion and context in the issue above.

CC @grst @davidsebfischer

**Comment by fmalmeida** [comment]
Hi Guys. Just to let you know that I am working on adding a module for that, which is also mentioned in issue #89
😄

**Comment by Zethson** [comment]
@fmalmeida it might make sense to make the module more general -> create scverse datastructures.
Especially with #99 the output should be MuData objects and not AnnData objects. Happy to get more detailed if you want me to.

**Comment by apeltzer** [comment]
Would be great to align here @fmalmeida with @Zethson 👍🏻

**Comment by grst** [comment]
Of course Lukas is right - but wouldn't it be a good start to add AnnData support and extend to mudata whenever we address #99?

I guess it depends if that feature is planned for the 2.1 release...

**Comment by Zethson** [comment]
@grst I also think that this is another great use case for the scverse IO package @ivirshup

**Comment by fmalmeida** [comment]
Hi @grst, @apeltzer and @Zethson.

Yes, the module I am writing is using scanpy from scverse IO package to handle convertion. It is basically done. I just need to find a working docker image for it (It is not in bioconda — helps on that are welcomed)

I believe we can do as Greg mentioned because they are different use cases.

I also saw that there is an issue #89 about converting to Seurat format (which I will also work on).

Since they are all diferente and valid use cases, I believe all of them should be options.

We can have modules for AnnData, Seurat and MuData. And later, if necessary, make then optional for users.

We could, for example, do:

1. First have AnnData
2. Have Seurat
3. Work on #99 and then add MuData.

What do you guys think?

**Comment by Zethson** [comment]
> Yes, the module I am writing is using scanpy from scverse IO package to handle convertion.

Well, the scverse IO package doesn't exist yet which is a common complaint :) You have to use scanpy as you were planning to do anyways.


"What do you guys think?"
Good plan!

**Comment by fmalmeida** [comment]
Thought scverse IO package when you mentioned was the whole scverse of functions 😅 

But they are actually planning to have everything as a single package? Is that so?

Anyways, monday I come back with my saga to find a docker image. The module itself is finished with scanpy 😃

Have a nice weekend guys

**Comment by Zethson** [comment]
"But they are actually planning to have everything as a single package? Is that so?"

"they" are the people you're talking to here :) Yes, this has been a frequent discussion.

**Comment by fmalmeida** [comment]
Didn’t know.
Great work on the packages 😁

**Comment by fmalmeida** [comment]
Hi Guys,
A question.

Is this module supposed to be cellranger only (cellranger subworkflow)? If not, how can I do conversion from other aligners. For example, `starsolo` does not seem to produce the required matrix, features and barcode files for scanpy.

**Comment by ivirshup** [comment]
AFAICT, start solo should output something like that? From the [bottom of the docs](https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md):

```
soloOutFileNames            Solo.out/          features.tsv barcodes.tsv        matrix.mtx
    string(s)               file names for STARsolo output:
                            file_name_prefix   gene_names   barcode_sequences   cell_feature_count_matrix
```

**Comment by fmalmeida** [comment]
Interesting ... 
This is not what I am seeing.

```bash
run_star
├── pipeline_info
│   ├── execution_report_2022-06-21_12-46-12.html
│   ├── execution_timeline_2022-06-21_12-46-12.html
│   ├── execution_trace_2022-06-21_12-46-12.txt
│   ├── pipeline_dag_2022-06-21_12-46-12.html
│   ├── samplesheet.valid.csv
│   └── software_versions.yml
└── star
    ├── Sample_X.Aligned.sortedByCoord.out.bam
    ├── Sample_X.Log.final.out
    ├── Sample_X.Log.out
    ├── Sample_X.Log.progress.out
    ├── Sample_X.SJ.out.tab
    ├── Sample_Y.Aligned.sortedByCoord.out.bam
    ├── Sample_Y.Log.final.out
    ├── Sample_Y.Log.out
    ├── Sample_Y.Log.progress.out
    ├── Sample_Y.SJ.out.tab
    └── star
        ├── Genome
        ├── Log.out
        ├── SA
        ├── SAindex
        ├── chrLength.txt
        ├── chrName.txt
        ├── chrNameLength.txt
        ├── chrStart.txt
        ├── exonGeTrInfo.tab
        ├── exonInfo.tab
        ├── geneInfo.tab
        ├── genomeParameters.txt
        ├── sjdbInfo.txt
        ├── sjdbList.fromGTF.out.tab
        ├── sjdbList.out.tab
        └── transcriptInfo.tab

3 directories, 32 files
```

**Comment by apeltzer** [comment]
Yeah because I think that the actual count generation is not done in the pipeline (yet). Could be added, I think this is just lacking some extra parameters / another step that generates the matrices that @ivirshup just mentioned above.

**Comment by grst** [comment]
Available in `dev` now!

**Comment by grst** [comment]
This should work for all aligners.
Also starsolo generates a count matrix in one way or the other (maybe h5?).
