### ISSUE TITLE
Demuxlet/Freemuxlet module

### ISSUE THREAD

**Issue by mikecuoco** [nf-core/scrnaseq#75]
## Describe the solution you'd like

An option to run [demuxlet or freemuxlet](https://github.com/statgen/popscle) ([Kang et al. 2018](https://www.nature.com/articles/nbt.4042)) with an input vcf file. These tools allow researchers to combine populations from different individuals into a single 10x channel and computationally deconvolve them, by using their genotypes (with demuxlet) or by naively looking for genetic differences (freemuxlet). The output from this module could be used to add labels to cells of the experiment and remove doublets.

## Describe alternatives you've considered

Running demuxlet/freemuxlet post-hoc on the bam file generated from this pipeline.

**Comment by grst** [comment]
I think this is out of scope for now. There's already the [Theislab/hadge](https://github.com/theislab/hadge) workflow for demultiplexing.
