### ISSUE TITLE
Chemistry/10X version detection

### ISSUE THREAD

**Issue by alexblaessle** [nf-core/scrnaseq#88]
# nf-core/scrnaseq feature request

## Is your feature request related to a problem? Please describe

Currently adding information about 10X version/chemistry is necessary. If this is not known a priori from the meta data, this might be helpful.

## Describe the solution you'd like

Just check the length of R1 (since the length of barcodes changed from 10Xv2 to 10Xv3).

**Comment by grst** [comment]
Newer versions of cellranger support autodetection of the protocol. This has been the default of the pipeline for a while, but now this is properly reflected in the pipeline documentation and default parameters.
