### ISSUE TITLE
Automatic conversion to h5ad/seurat files after alignment.

### ISSUE THREAD

**Issue by alexblaessle** [nf-core/scrnaseq#89]
## Is your feature request related to a problem? Please describe

h5ad/seurat are becoming default file formats for scRNAseq. It would be nice if the pipeline outputs one of the two or even both.

## Describe the solution you'd like

Output to h5ad and seurat (could be controllable via a flag.)

**Comment by grst** [comment]
There's already an issue for h5ad: #68 
Will address that soon!

**Comment by nh13** [comment]
Would like this too!

**Comment by apeltzer** [comment]
Addressed in the to-be-released 2.1.0 release now 👍🏻
