### ISSUE TITLE
Implement tests with nf-test

### ISSUE THREAD

**Issue by grst** [nf-core/scrnaseq#91]
Pytest workflow makes it easier to maintain larger test suites and also allows to check outputs. 

cf. https://github.com/nf-core/tools/issues/605, https://github.com/nf-core/rnaseq/pull/546, https://github.com/nf-core/sarek/tree/dev/tests

Testing scenarios: 
 * Run pipeline with more than one file
 * different parameter combinations
 * different filenames and folder structures for cellranger
 * run subworkflows with and without index
 * different protocols, if we manage to get the test files

**Comment by grst** [comment]
I'm pretty sure the latest bugs in 2.5.0 would have been caught by that. 

@fmalmeida, do you already have something in the internal pipeline that you could upstream here?

**Comment by fmalmeida** [comment]
Is there a nf-core pipeline already standardized with nf-test so that I can "copy" the same standards in terms of organization and setup?

**Comment by grst** [comment]
e.g. https://github.com/nf-core/ampliseq/tree/dev or https://github.com/nf-core/spatialtranscriptomics, but not sure if this qualifies as "standardized".

Modules can since very recently be tested with nf-test in nf-core/modules. There's even documentation for that https://nf-co.re/docs/contributing/modules#writing-nf-test-tests

**Comment by grst** [comment]
Is there a PR I can look at 👀?

**Comment by fmalmeida** [comment]
Did not open, is still in the branch (shown in the right menu)

I can open a draft if you prefer.

**Comment by grst** [comment]
I see, thanks! I opened one now, makes it easier to discuss...

**Comment by fmalmeida** [comment]
Hello hello,
This was merged/solved by #291
