### ISSUE TITLE
Samplesheet standard

### ISSUE THREAD

**Issue by grst** [nf-core/scrnaseq#92]
From [slack](https://nfcore.slack.com/archives/CHN5BV5DW/p1643300397053900):

I'm wondering how the samplesheet for scrnaseq should look like that it works for all four pipeline branches (kb/alevin/starsolo/cellranger):

### Input files

-  one line per sample (e.g. pointing to a folder with technical replicates) or one line per fastq file? (the latter is used by #rnaseq, and more IMO more explicit and less error-prone)
-  kb, alevin and starsolo expect a pair (R1/R2) of fastq files. Alevin can merge technical replicates automatically, for the other two I couldn't figure out yet if that's possible.
-  cellranger expects a folder structure with one folder per sample which contains all technical replicates. If the technical replicates were sequenced on different flow cells, the same sample (or "gem") can even be distributed over multiple folders. 

### metadata

-  sample id
-  protocol (currently this is a global option)?
-  expectCells, on a per sample basis

**Comment by grst** [comment]
* Use CSV format
 * metadata as above
    - [ ] other columns relevant? 
 * cellranger: create folder structure from samplesheet and rename files if necessary

**Comment by apeltzer** [comment]
Resolved in https://github.com/nf-core/test-datasets#469

**Comment by apeltzer** [comment]
Resolved in https://github.com/nf-core/test-datasets#469
