### ISSUE TITLE
Get Alevin seg fault when reading from sample spreadsheet

### ISSUE THREAD

**Issue by SarahBeecroft** [nf-core/scrnaseq#98]
## Description of the bug
When running the pipeline using Alevin, I get the following error:
```bash
.command.sh: line 2: 551040 Segmentation fault      (core dumped) salmon alevin -l ISR -1 samplesheet.csv -2 null --chromium -i salmon_index -o samplesheet_alevin_results -p 8 --tgMap txp2gene.tsv --dumpFeatures –-dumpMtx
```
However, when I run Alevin directly (conda install) with the fastq files supplied directly, it works, eg:

```bash
salmon alevin -l ISR -1 data/SRR18163494_1.fastq.gz -2 data/SRR18163494_2.fastq.gz --chromium -i salmon_index -o samplesheet_alevin_results -p 8 --tgMap txp2gene.tsv --dumpFeatures –-dumpMtx
```
I think it might be something to do with Alevin not being able to parse the sample sheet? Have I made an obvious mistake or is this a genuine bug? 

## Steps to reproduce

Steps to reproduce the behaviour:
Command line:
``` bash
nextflow run nf-core/scrnaseq -r 1.1.0 \
    --input samplesheet.csv --fasta GRCh38.primary_assembly.genome.fa \
    --gtf gencode.v39.primary_assembly.annotation.gtf \
    -profile singularity,slurm -c custom_profile.conf
```

Samplespreadsheet.csv: (I have tried with and without headers, different strandedness)
```
sample,fastq_1,fastq_2,strandedness
SRR18163494,data/SRR18163494_1.fastq.gz,data/SRR18163494_2.fastq.gz,unstranded
SRR18163495,data/SRR18163495_1.fastq.gz,data/SRR18163495_2.fastq.gz,unstranded
```
Error:
```bash
.command.sh: line 2: 551040 Segmentation fault      (core dumped) salmon alevin -l ISR -1 samplesheet.csv -2 null --chromium -i salmon_index -o samplesheet_alevin_results -p 8 --tgMap txp2gene.tsv --dumpFeatures –-dumpMtx
```
## Expected behaviour
I had expected this step to run to completion.

## Log files
[nextflow_log_cloud.txt](https://github.com/nf-core/scrnaseq/files/8510019/nextflow_log_cloud.txt)

## System

- Hardware:  This error is the same on both cloud and HPC
- Executor:  Have used slurm (HPC) and local (cloud)
- OS:   Linux ubuntu

## Nextflow Installation

- Version:  21.10.0

## Container engine

- Engine:  Singularity
- Image tag:  nfcore/scrnaseq:1.1.0

**Comment by SarahBeecroft** [comment]
Hi, Sorry for late reply, didn't see the GitHub notification. I haven't gone back to trying this, but if you are updating to alevin-fry soon then I won't worry too much about this issue. Thanks for getting back to me.

**Comment by grst** [comment]
Closing this as alevin-fry is now available from `dev`. Please open a new issue if you encounter any problems with it!
