### ISSUE TITLE
Add support for CITE-seq data processing

### ISSUE THREAD

**Issue by drpatelh** [nf-core/scrnaseq#99]
As suggested by @grst on Slack: "Once we have cellranger, it should also support (10x) cite-seq out-of-the-box. IDK how difficult it would be to support this with the other aligners."

It appears that we already have a modules for [`cellranger`](https://github.com/nf-core/scrnaseq/tree/dev/modules/nf-core/modules/cellranger) in the `dev` version of the pipeline.

**Comment by rob-p** [comment]
Cc'ing @k3yavi who should be able to give good direction for CITE-seq support using `alevin-fry`.

**Comment by ggabernet** [comment]
Hi, I'll work on CITE-seq support using `cellranger multi`, there are example datasets and I've done this analysis before. For `alevin-fry`, I'll let someone else with more experience work on it 😄

**Comment by grst** [comment]
note: when adding CITEseq, the `AnnData` output should be extended to a corresponding [`MuData`](https://muon.readthedocs.io/en/latest/notebooks/quickstart_mudata.html) object. See also discussion in #68

**Comment by vd4mmind** [comment]
> Hi, I'll work on CITE-seq support using `cellranger multi`, there are example datasets and I've done this analysis before. For `alevin-fry`, I'll let someone else with more experience work on it 😄

Hi @ggabernet ,  We are starting with NextFlow journey and thanks for making this 10x pipeeline. 

Can you let guide if the prod version 2.5.1 has `cellranger multi` ? We would need to test Chromium GEM-X Single Cell 5' v3 Gene Expression with Feature Barcoding technology, that has Gene Expression (GEX), Feature Barcode Antibody Capture (FB), T cell receptor (TCR), and B cell receptor (BCR).

**Comment by grst** [comment]
cellranger multi is implemented. There might still be rough edges, but please open separate issues if you encounter any. 
Same if you are interested in support by other aligners (e.a. alevin-fry).
